name: Tinybird - Recommendations Workflow

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Generate recommendations
        run: python load.py
        with:
          TB_APPEND_TOKEN: ${{ secrets.TB_APPEND_TOKEN }}
          TB_READ_TOKEN: ${{ secrets.TB_READ_TOKEN }}
          TB_HOST: https://api.us-east.tinybird.co
